"use strict";

var _ = require('dry-underscore');

var db_class = require('../');

var eq = _.test.eq;
var ok = _.test.ok;

suite('db');

function no_id(docs){
    if(_.isArray(docs)){
        return _.map(docs, no_id);
    }
    return _.omit(docs, "_id");
}

test("no_id", function(){
    eq(no_id({ _id: "bad", foo: true }), { foo: true });
    eq(no_id([{ _id: "bad", foo: true }, { _id: "bad", bar: true }]), [{ foo: true }, { bar: true }]);
});

function one(v){ return(_.jclone({ id: 1, value: _.undef(v) ? 1 : v })); }
function two(v){ return(_.jclone({ id: 2, value: _.undef(v) ? 2 : v })); }
function three(v){ return(_.jclone({ id: 3, value: _.undef(v) ? 3 : v })); }
function docs(){ return([ one(), two(), three() ]); }

test('collections', function(done){

    var cols = { foo: true, bar: true };

    var db = new db_class(cols);

    eq(db.collections(), cols);

    db.foo.index("_id", done);

});

test("find", function(done){

    var db = new db_class({ test: true });

    await{ db.test.remove(_.plumb(defer(), done)); }

    await{ db.test.insert(docs(), _.plumb(defer(), done)); }

    var results = null;

    await{ db.test.find(_.plumb(defer(results), done)); }

    eq(no_id(results), docs());

    await{ db.test.find({ id: 1 }, _.plumb(defer(results), done)); }

    eq(no_id(results), [one()]);

    await{ db.test.find_one({ id: 1 }, _.plumb(defer(results), done)); }

    eq(no_id(results), one());

    await{ db.test.find_one({ id: "not-found" }, _.plumb(defer(results), done)); }

    eq(results, null);

    done();
});

test("update", function(done){

    var db = new db_class({ test: true });

    await{ db.test.remove(_.plumb(defer(), done)); }

    await{ db.test.insert(docs(), _.plumb(defer(), done)); }

    var results = null;

    await{ db.test.find(_.plumb(defer(results), done)); }

    eq(no_id(results), docs());

    await{ db.test.update({ id: { $in: [1, 2] } }, { $set: { value: 4 } }, { multi: true, safe: true }, _.plumb(defer(results), done)); }

    await{ db.test.find(_.plumb(defer(results), done)); }

    await{ db.test.find({ id: { $in: [1, 2] } }, _.plumb(defer(results), done)); }

    eq(no_id(results), [one(4), two(4)]);

    await{ db.test.update_one({ id: "not-found" }, { id: { $set: "found" } }, _.plumb(defer(results), done)); }

    eq(results, null);

    await{ db.test.update_one({ id: 1 }, { $set: { value: 6 } }, { new: true }, _.plumb(defer(results), done)); }

    eq(no_id(results), one(6));

    await{ db.test.find_one({ id: 1 }, _.plumb(defer(results), done)); }

    eq(no_id(results), one(6));

    done();
});

